version: '3'
services:
  # Services
  redis:
    image: "redis:alpine"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  zookeeper:
    image: "zookeeper"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    #   PGDATA: /var/lib/postgresql/data
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    # ports:
    #   - '172.17.0.1:5432:5432'
    # volumes:
    #   - ./servers.json:/pgadmin4/servers.json

  # Admin Services
  pgadmin:
    image: "elestio/pgadmin:REL-9_8"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "andor.gunczer@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  # redis-commander:
  #   image: ""
  